import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    nav: {
      routine: 'Rotina de Treino',
      progress: 'Evolução e PDF',
      feed: 'Feed de Conquistas',
      wearable: 'Sincronizar Relógio',
      coach: 'Controle de Alunos',
      settings: 'Ajustes do App',
      logout: 'Sair da Aplicação',
    },
    auth: {
      roleSelector: 'Selecione seu Perfil principal',
      student: 'Aluno / Atleta',
      studentDesc: 'Acesse seus treinos prescritos ou crie rotinas de exercícios personalizadas.',
      coach: 'Professor / Coach',
      coachDesc: 'Gerencie alunos, prescreva fichas de treinos completas e acompanhe progresso.',
      welcomeTitle: 'Treino Inteligente e Sincronizado',
      welcomeSubtitle: 'Seu diário esportivo pessoal com integração de wearables e prescrição inteligente.',
      loginTitle: 'Acesse sua Conta',
      registerTitle: 'Crie sua Conta Grátis',
      email: 'Conta de E-mail',
      password: 'Senha de Acesso',
      name: 'Nome Completo',
      age: 'Idade',
      weight: 'Peso (kg)',
      height: 'Altura (cm)',
      health: 'Problemas ou Restrições de Saúde',
      healthPlaceholder: 'Ex: Hérnia de disco, asma, sem restrições...',
      level: 'Nível de Treino Atual',
      levelBeginner: 'Iniciante',
      levelIntermediate: 'Intermediário',
      levelAdvanced: 'Avançado',
      objective: 'Qual seu Objetivo Principal?',
      objectiveHypertrophy: 'Hipertrofia (Massa)',
      objectiveLoss: 'Definição & Emagrecimento',
      objectiveStrength: 'Força Máxima',
      objectiveResistance: 'Resistência / Cardio',
      referralLink: 'Possui Código do seu Treinador?',
      referralPlaceholder: 'ID do Treinador (Opcional)',
      hasAccount: 'Já possui uma conta?',
      noAccount: 'Não tem uma conta?',
      signIn: 'Acessar Plataforma',
      signUp: 'Efetuar Cadastro',
      googleSignIn: 'Acessar com o Google',
      studentIdNotice: 'Este é o seu código de estudante:',
      consentLabel: 'Consentimento de Proteção de Dados (LGPD/RGPD):',
      consentBrief: 'Aceito o processamento e armazenamento de segurança dos meus indicadores físicos...',
      consentClickRead: 'Clique para ler e aceitar o termo completo.',
      modalTitle: 'Consentimento de Dados Pessoais',
      modalSubtitle: 'Regulamento Geral de Proteção de Dados (LGPD/RGPD)',
      modalIntro: 'O Treino Inteligente (RLL Solutions) leva a confidencialidade e a segurança das suas informações de saúde com o máximo rigor científico e ético. De acordo com a Lei Geral de Proteção de Dados (LGPD) e o Regulamento Geral sobre a Proteção de Dados (RGPD), os dados desportivos e clínico-fisiológicos necessitam do seu consentimento explícito para processamento.',
      modalSec1Title: '1. Tipos de Informação Processada:',
      modalSec1Text: 'Recolhemos os seus dados de rastreamento físico (peso, altura, idade e nível desportivo), objetivos gerais de evolução, logs e históricos de treino diários, e quaisquer restrições médico-fisiológicas relevantes (problemas de postura, patologias ou dores musculares) indicadas livremente por si na ficha de perfil ou fornecidas pelo seu dispositivo wearable.',
      modalSec2Title: '2. Finalidades Legais e Clínicas:',
      modalSec2Text: 'O processamento destas métricas sensíveis serve exclusivamente para adaptar e personalizar as fichas e rotinas de exercícios de forma estritamente individual através de nosso algoritmo preditivo inteligente, prevenindo lesões e gerando cargas adequadas, assim como permitir a análise gráfica do seu progresso desportivo real pelo seu treinador ou consultor associado.',
      modalSec3Title: '3. Confidencialidade e Armazenamento Controlado:',
      modalSec3Text: 'As suas informações de saúde são armazenadas localmente no registo seguro do navegador e sincronizadas de forma anônima. Nenhuma de suas informações será vendida, transferida ou partilhada com empresas terceiras de publicidade ou marketing. Se estiver vinculado a um treinador pessoal por meio de link específico, os dados serão partilhados apenas com esse profissional autorizado.',
      modalSec4Title: '4. Livre Revogação e Exclusão Instantânea:',
      modalSec4Text: 'Compreendo que posso, a qualquer momento, revogar livremente este consentimento, consultar detalhadamente, alterar ou ordenar a eliminação permanente e completa de todo o meu histórico de treinos e indicadores físicas diretamente na área de Configurações, removendo imediatamente todos os meus vestígios digitais de saúde da aplicação.',
      modalSec5Title: '5. Termos do Consentimento Livre e Esclarecido:',
      modalSec5Text: 'Ao clicar no botão "Aceitar e Confirmar", declara concordar voluntariamente com a recolha, tratamento e o armazenamento criptografado seguro dos seus dados de fitness descritos acima para a finalidade única de personalização do seu programa de treinos diários.',
      btnCancel: 'Cancelar',
      btnAccept: 'Aceitar e Confirmar',
    },
    settings: {
      title: 'Ajustes do App',
      profileTitle: 'Configurações do Perfil',
      profileDesc: 'Gerencie suas informações de login, indicadores físicos e foto de perfil privada.',
      displayTitle: 'Preferências de Exibição / Idioma',
      languageSelect: 'Idioma do Aplicativo',
      darkMode: 'Acessibilidade Visual (Modo Escuro)',
      darkModeDesc: 'Ajusta o contraste para ambientes escuros',
      forcedOffline: 'Modo Offline Forçado',
      forcedOfflineDesc: 'Executa o app de forma autônoma sem rede (Conserva dados)',
      notificationsTitle: 'Lembretes de Treino Diários',
      notificationsDesc: 'Configure notificações de lembrete customizadas para manter seu foco nos treinos.',
      notifTime: 'Hora do Lembrete',
      notifDays: 'Dias de Notificação',
      notifPhrase: 'Frase Motivadora Personalizada',
      btnSaveNotif: 'Salvar Notificações',
      levelTitle: 'Mudar Nível de Treino',
      levelDesc: 'A IA e o gerador adaptam o volume dependendo do seu condicionamento.',
      goalTitle: 'Alterar Objetivo Fitness',
      goalDesc: 'Altere seu foco para focar os novos treinos no seu objetivo desejado.',
      saveProfile: 'Salvar Alterações do Perfil',
      changePhoto: 'Mudar Foto de Perfil',
      changePhotoDesc: 'Toque na imagem acima para carregar do seu dispositivo (JPG/PNG) ou cole um link direto da web no campo abaixo.',
      photoPlaceholder: 'Link/URL da Imagem',
      btnFile: 'Ficheiro',
      btnLogOut: 'Sair / Trocar de Conta',
      premiumActive: 'Membro Premium',
      premiumInactive: 'Plano Gratuito Lite',
      premiumTitleActive: 'Treine Sem Limites Offline!',
      premiumTitleInactive: 'Experimente o Treino Inteligente Pro',
      premiumDesc: 'Acesso ilimitado ao gerador de treinos musculares, download ilimitado para treinos sem conexão, exportação de PDF de análise e comunidade liberada.',
      btnPremiumActive: 'Mudar para Plano Grátis',
      btnPremiumInactive: 'Ativar Modo Premium de Graça',
      rightsTitle: 'Manual de Direitos & Proteção de Dados',
      rightsSubtitle: 'LGPD (Lei nº 13.709/2018) & RGPD Aplicado',
      rightsBtn: 'Direitos LGPD',
      exportBtn: 'Portabilidade (JSON)',
      clearBtn: 'Apagar Dados',
    },
    workout: {
      mySheet: 'Minha Ficha de Treino',
      desc: 'Visualize sua ficha prescrita pelo treinador, gere novas fichas de treino personalizadas com inteligência artificial, pesquise tutoriais e registre seu progresso.',
      startWorkout: 'Iniciar Treino Prescrito',
      generateAI: 'Gerador IA Inteligente',
      searchRoutine: 'Buscar exercício na rotina atual...',
      noMatchRoutine: 'Nenhum exercício na rotina corresponde ao termo ',
      clearSearch: 'Limpar busca',
      viewAll: 'Ver todos',
      dayTabAll: 'Todos os Dias',
      instructionTitle: 'Instruções Especiais do Treinador',
      noInstructions: 'Foco técnico na execução e amplitude dos movimentos!',
      addCustomExercise: 'Adicionar exercício avulso à ficha',
      addBtn: 'Adicionar',
      searchExercisePlaceholder: 'Buscar exercícios na videoteca...',
      noExercisesFoundTitle: 'Vícleo de Exercícios',
      noExercisesFoundDesc: 'Nenhum exercício encontrado para ',
      clearLibrarySearch: 'Limpar Biblioteca',
      activeWorkout: 'Treino Ativo em Progresso',
      concluded: 'CONCLUÍDO',
      exerciseCount: 'EXERCÍCIO {current} de {total}',
      tips: '💡 Dicas profissionais de biomecânica:',
      sets: 'Séries',
      reps: 'Repetições',
      rest: 'Descanso',
      loadLabel: 'Carga:',
      loadPlaceholder: 'Ex: 20kg',
      setsTracker: 'Séries concluídas neste exercício:',
      previousLoad: 'Carga anterior registrada:',
      weightTrackerPrompt: 'Informa a carga para acompanhar progressão!',
      finishWorkout: 'Registrar & Finalizar Treino',
      workoutComplete: 'Treino Completo!',
      nextExercise: 'Próximo Exercício',
      congratulations: 'Parabéns!',
      doneWord: 'concluído',
      allDone: 'Excelente trabalho!',
    },
    progress: {
      title: 'Evolução e PDF',
      desc: 'Visualize seu progresso físico-desportivo de médio prazo, seu histórico de fidelidade de treinos concluídos e exporte relatórios PDF detalhados.',
      exportPdf: 'Exportar Relatório Geral de Treinos (PDF)',
      recentWorkouts: 'Histórico de Treinos Registados',
      noWorkouts: 'Nenhum treino registado ainda. Conclua os treinos para ver seu progresso aqui!',
      statsCards: {
        activeDays: 'Frequência de Exercício',
        calories: 'Gasto Energético Estimado',
        avgDuration: 'Duração Média das Sessões',
        avgHeartRate: 'Rastreio Cardíaco Médio',
        streak: 'Firmeza e Streak Atual',
        days: 'dias ativos',
        minutes: 'minutos',
        bpm: 'bpm',
        sessions: 'séries terminadas',
      }
    },
    wearable: {
      title: 'Sincronizar Relógio',
      desc: 'Integre dados de wearables de última geração (Apple Watch, Garmin, Fitbit) para rastrear frequência cardíaca em tempo real e calorias ativas acumuladas.',
      connected: 'Sincronizador Ativo',
      disconnected: 'Não Sincronizado',
      statusConnected: 'Dispositivo conectado e recebendo biométricas da sessão.',
      statusDisconnected: 'Por favor, selecione seu wearable acima para iniciar a telemetria ao vivo.',
      deviceLabel: 'Dispositivo Wearable:',
      appleWatch: 'Apple Watch',
      garmin: 'Garmin Watch',
      fitbit: 'Fitbit',
      none: 'Nenhum / Desconectar',
      metrics: {
        steps: 'Passos Diários',
        heartRate: 'Batimentos (FC)',
        calories: 'Calorias Ativas',
        lastSync: 'Última Atualização:',
        syncNow: 'Sincronizar Agora',
      }
    },
    feed: {
      title: 'Feed de Conquistas',
      desc: 'Partilhe o seu esforço, comemore o sucesso dos seus colegas de ginásio e mantenha-se motivado com atualizações em tempo real da nossa comunidade integrada.',
      placeholder: 'Partilhe uma conquista, frase motivadora ou nova carga... (Ex: Hoje bati 90kg no supino!)',
      postButton: 'Publicar Conquista',
      like: 'Gostar',
      likes: 'Gostos',
      comment: 'Comentar...',
      noPosts: 'Nenhuma postagem no feed ainda. Seja o primeiro a motivar a comunidade!',
    },
    coach: {
      title: 'Painel de Gestão do Coach',
      desc: 'Escreva prescrições inteligentes de exercícios, configure dias de treino (Dia A, B, C...) e consulte de forma bidirecional os relatórios, pesos e as métricas clínicas de saúde dos seus atletas licenciados.',
      addStudent: 'Vincular Novo Atleta / Estudante',
      studentIdPlaceholder: 'ID do Estudante (Ex: STU-1234)',
      btnLink: 'Vincular Aluno',
      linkedStudents: 'Atletas e Alunos Vinculados ({count})',
      noStudents: 'Nenhum aluno vinculado ao seu perfil. Forneça o seu ID ou vincule um ID de aluno para monitorizar!',
      lastAccess: 'Último Acesso:',
      age: 'Idade:',
      weight: 'Peso:',
      height: 'Altura:',
      health: 'Restrições clínicas:',
      objectives: 'Foco desportivo:',
      experience: 'Nível:',
      prescribe: 'Prescrever Ficha de Treino para {name}',
      routineTitle: 'Título da Planilha de Exercícios:',
      addExerciseRow: '+ Adicionar Linha de Exercício',
      exerciseName: 'Nome do Exercício',
      sets: 'Séries',
      reps: 'Reps',
      rest: 'Descanso',
      load: 'Carga Prescrita',
      observation: 'Observações / Postura...',
      day: 'Dia / Divisão',
      btnPrescribeSheet: 'Publicar e Enviar Ficha de Treino',
    }
  },
  en: {
    nav: {
      routine: 'Workout Routine',
      progress: 'Progress & PDF',
      feed: 'Achievement Feed',
      wearable: 'Sync Smartwatch',
      coach: 'Student Control',
      settings: 'App Settings',
      logout: 'Sign Out',
    },
    auth: {
      roleSelector: 'Select your main Profile',
      student: 'Student / Athlete',
      studentDesc: 'Access your prescribed workouts or create custom personalized routines.',
      coach: 'Professor / Coach',
      coachDesc: 'Manage students, prescribe complete training sheets, and monitor progress.',
      welcomeTitle: 'Intelligent & Synced Workout',
      welcomeSubtitle: 'Your personal digital sports diary with wearable integration and intelligent prescription.',
      loginTitle: 'Access Your Account',
      registerTitle: 'Create Your Free Account',
      email: 'Email Account',
      password: 'Access Password',
      name: 'Full Name',
      age: 'Age',
      weight: 'Weight (kg)',
      height: 'Height (cm)',
      health: 'Health Issues or Constraints',
      healthPlaceholder: 'E.g., Herniated disc, asthma, no restrictions...',
      level: 'Current Fitness Level',
      levelBeginner: 'Beginner',
      levelIntermediate: 'Intermediate',
      levelAdvanced: 'Advanced',
      objective: 'What is your Main Goal?',
      objectiveHypertrophy: 'Hypertrophy (Muscle Gain)',
      objectiveLoss: 'Definition & Weight Loss',
      objectiveStrength: 'Maximum Strength',
      objectiveResistance: 'Endurance / Cardio',
      referralLink: 'Do you have a Coach ID?',
      referralPlaceholder: 'Coach ID (Optional)',
      hasAccount: 'Already have an account?',
      noAccount: 'Join now for free!',
      signIn: 'Access Platform',
      signUp: 'Complete Registration',
      googleSignIn: 'Access with Google',
      studentIdNotice: 'This is your unique student ID:',
      consentLabel: 'Data Protection Consent (LGPD/GDPR):',
      consentBrief: 'I accept the secure processing and storage of my physical and health metrics...',
      consentClickRead: 'Click to read and accept the full terms.',
      modalTitle: 'Personal Data Consent',
      modalSubtitle: 'General Data Protection Regulation (GDPR / LGPD)',
      modalIntro: 'Intelligent Workout (RLL Solutions) takes the privacy and security of your health information with utmost scientific and ethical rigor. Under the General Data Protection Regulation (GDPR) and Brazilian LGPD, clinical, health or sports metrics require your explicit consent for processing.',
      modalSec1Title: '1. Processed Data Categories:',
      modalSec1Text: 'We collect your physical tracking data (weight, height, age, and fitness level), session progress logs, workout history, custom load records, and any medical restrictions (postural constraints, joint pains, injuries) you freely input or sync through your wearable device.',
      modalSec2Title: '2. Legal and Clinical Purposes:',
      modalSec2Text: 'The processing of these sensitive health metrics is solely intended to tailor, adjust and personalize your physical routines via our smart predictive algorithm, minimizing injury risks and prescribing proportional loads, as well as enabling visual progress tracking by your assigned personal trainer.',
      modalSec3Title: '3. Security and Controlled Data custody:',
      modalSec3Text: 'Your health records are stored in browser-level encrypted local states or synchronized anonymously. Under no circumstances will your information be shared with, sold to, or cross-referenced by third-party advertising networks. If vinculated with a coach, they hold strictly professional access.',
      modalSec4Title: '4. Free Revocation and Instant Deletion:',
      modalSec4Text: 'I understand that I can withdraw this consent at any point, query my saved metadata, edit, or command the complete, irrevocable deletion of all my physical metrics and logs directly inside the Settings tab, leaving no trace in the system databases.',
      modalSec5Title: '5. Terms of Informed Consent:',
      modalSec5Text: 'By clicking "Accept and Confirm", you voluntarily declare agreement to the collection, processing, and encrypted storage of your physical fitness information described above for the unique purpose of your personalized daily workouts.',
      btnCancel: 'Cancel',
      btnAccept: 'Accept and Confirm',
    },
    settings: {
      title: 'App Settings',
      profileTitle: 'Profile Configuration',
      profileDesc: 'Manage your login credentials, biological indicators, and private avatar picture.',
      displayTitle: 'Interface Preferences / Language',
      languageSelect: 'Application Language',
      darkMode: 'Visual Accessibility (Dark Mode)',
      darkModeDesc: 'Adjusts contrast for high & low light comfort',
      forcedOffline: 'Force Offline Emulator',
      forcedOfflineDesc: 'Emulate network loss and offline sync capabilities autonomously',
      notificationsTitle: 'Daily Workout Reminders',
      notificationsDesc: 'Configure scheduled local reminder messages to stay focused on your workouts.',
      notifTime: 'Reminder Time',
      notifDays: 'Active Calendar Days',
      notifPhrase: 'Custom Motivational Reminder Message',
      btnSaveNotif: 'Save Notification Settings',
      levelTitle: 'Change Training Intensity',
      levelDesc: 'AI and engine adjust volume and density based on your current readiness.',
      goalTitle: 'Change Main Fitness Goal',
      goalDesc: 'Switch focus to recalculate parameters and target zones dynamically.',
      saveProfile: 'Save Profile Changes',
      changePhoto: 'Change Profile Picture',
      changePhotoDesc: 'Tap on the avatar bubble to upload locally (JPG/PNG) or type a direct image URL below.',
      photoPlaceholder: 'Direct Image Link/URL',
      btnFile: 'File Selector',
      btnLogOut: 'Sign Out / Switch User',
      premiumActive: 'Premium Member',
      premiumInactive: 'Free Lite Plan',
      premiumTitleActive: 'Work out with No Limits Offline!',
      premiumTitleInactive: 'Try Intelligent Workout Pro',
      premiumDesc: 'Unlimited access to the muscle routines generator, unlimited offline downloads, advanced PDF analytics export, and community access unlocked.',
      btnPremiumActive: 'Switch to Free Plan',
      btnPremiumInactive: 'Activate Premium Mode Free',
      rightsTitle: 'Data Protection & Rights Manual',
      rightsSubtitle: 'GDPR / LGPD Compliance Handbook',
      rightsBtn: 'GDPR Rights',
      exportBtn: 'Data Portability (JSON)',
      clearBtn: 'Erase Profile',
    },
    workout: {
      mySheet: 'My Training Routine',
      desc: 'View your routine prescribed by your coach, generate new personalized AI workouts, search exercises library, and log your progress.',
      startWorkout: 'Start Prescribed Session',
      generateAI: 'Generate with Smart AI',
      searchRoutine: 'Search exercise in current routine...',
      noMatchRoutine: 'No exercises in your routine match the term ',
      clearSearch: 'Clear search',
      viewAll: 'View all',
      dayTabAll: 'All Days',
      instructionTitle: 'Special Coach Guidelines',
      noInstructions: 'Technical precision on range of motion and form is recommended!',
      addCustomExercise: 'Add custom isolated exercise to sheet',
      addBtn: 'Add Exercise',
      searchExercisePlaceholder: 'Search videoteca tutorials...',
      noExercisesFoundTitle: 'Exercise Library',
      noExercisesFoundDesc: 'No exercises found matching ',
      clearLibrarySearch: 'Clear Library Search',
      activeWorkout: 'Active Workout in Progress',
      concluded: 'COMPLETED',
      exerciseCount: 'EXERCISE {current} of {total}',
      tips: '💡 Professional biomechanics tips:',
      sets: 'Sets',
      reps: 'Repetitions',
      rest: 'Rest Interval',
      loadLabel: 'Load:',
      loadPlaceholder: 'E.g., 20kg',
      setsTracker: 'Séries completed in this exercise:',
      previousLoad: 'Previous weight logged:',
      weightTrackerPrompt: 'Input your active load to track progression!',
      finishWorkout: 'Save & Finish Session',
      workoutComplete: 'Workout Completed!',
      nextExercise: 'Next Exercise',
      congratulations: 'Congratulations!',
      doneWord: 'completed',
      allDone: 'Excellent work!',
    },
    progress: {
      title: 'Progress & PDF Exports',
      desc: 'Visualize your medium-term athletic progress and statistics, review your completed sessions log, and export rich PDF analytics summaries.',
      exportPdf: 'Export Comprehensive Progress Report (PDF)',
      recentWorkouts: 'Saved Sessions History Log',
      noWorkouts: 'No sessions registered yet. Complete active sessions to unlock progress analytics here!',
      statsCards: {
        activeDays: 'Exercise Consistency',
        calories: 'Estimated Caloric Burn',
        avgDuration: 'Average Session Duration',
        avgHeartRate: 'Average Cardiac Track',
        streak: 'Daily Consistency Streak',
        days: 'active days',
        minutes: 'minutes',
        bpm: 'bpm',
        sessions: 'sets completed',
      }
    },
    wearable: {
      title: 'Sync Smartwatch',
      desc: 'Integrate state-of-the-art consumer wearables (Apple Watch, Garmin, Fitbit) to trace system live heart rates and active cumulative calories.',
      connected: 'Sync Link Active',
      disconnected: 'Sync Disconnected',
      statusConnected: 'Wearable device linked and streaming telemetry parameters.',
      statusDisconnected: 'Select or tap your default wearable options above to initialize live sensor streams.',
      deviceLabel: 'Select Smartwatch:',
      appleWatch: 'Apple Watch',
      garmin: 'Garmin Watch',
      fitbit: 'Fitbit',
      none: 'None / Disconnect',
      metrics: {
        steps: 'Daily Metric Steps',
        heartRate: 'Beats per Minute (HR)',
        calories: 'Active Calories',
        lastSync: 'Last Calibrated Sync:',
        syncNow: 'Sync Active Sensors',
      }
    },
    feed: {
      title: 'Achievement Community',
      desc: 'Share your efforts, applaud gym peer milestones, and stay fueled with instantaneous social feed indicators.',
      placeholder: 'Share an achievement, workout quote or personal record... (E.g., Lifted 90kg on Bench Press today!)',
      postButton: 'Publish Achievement',
      like: 'Like',
      likes: 'Likes',
      comment: 'Write a comment...',
      noPosts: 'No achievements posted yet. Be the first to fuel this feed!',
    },
    coach: {
      title: 'Coach Management Control',
      desc: 'Prescribe digital exercise sheets, divide workout days (Splits A, B, C...) and review synced progress reports, physical health records and active weight loads from linked athletes.',
      addStudent: 'Link New Student Profile',
      studentIdPlaceholder: 'Student Unique ID (E.g., STU-1234)',
      btnLink: 'Link Athlete Profile',
      linkedStudents: 'Licensed Athletes & Students ({count})',
      noStudents: 'No students linked to your profile page yet. Provide your coach ID or link a student ID to begin monitoring!',
      lastAccess: 'Last Opened System App:',
      age: 'Age:',
      weight: 'Weight:',
      height: 'Height:',
      health: 'Clinical limitations:',
      objectives: 'Athletic pursuit:',
      experience: 'Fitness state:',
      prescribe: 'Draft Workout Routine for {name}',
      routineTitle: 'Routine / Program Title:',
      addExerciseRow: '+ Append Exercise Row',
      exerciseName: 'Exercise name',
      sets: 'Sets',
      reps: 'Reps',
      rest: 'Rest',
      load: 'Assigned Load',
      observation: 'Coaching observations & notes...',
      day: 'Target Split / Day',
      btnPrescribeSheet: 'Publish & Transmit Workout Sheet',
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Read saved language preference or default to browser setting
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    if (saved === 'en' || saved === 'pt') return saved as Language;
    return 'pt'; // Default to pt
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let current: any = translations[language];
    for (const k of keys) {
      if (current && typeof current === 'object' && k in current) {
        current = current[k];
      } else {
        return key; // Fallback
      }
    }
    return typeof current === 'string' ? current : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
